### ISSUE TITLE
404 for browser-client.js, when following the Quick Start Guide

### ISSUE THREAD

**Issue by nebulade** [zazukoians/boomerang-server#1]
Running through the Quick Start Guide in the Readme.md reveals a 404 when accessing https://localhost:8443/client/ as the code only statically serves up `node_modules/boomerang-client/dist/` while the requested `browser-client.js` resides in `node_modules/boomerang-client` only.

There might be a build step missing for boomerang-client, which is triggered on postinstall?

**Comment by bergos** [comment]
I added the missing browserify package to the dependencies and fixed the build script to log messages on errors.
